{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# PROYECTO DE MACHINE LEARNING: PREDICCIÓN DEL VALOR DE LAS VIVIENDAS PREFABRICADAS 🏠💶\n",
    "\n",
    "Bienvenidos a este proyecto de Machine Learning, centrado en la predicción del valor en euros de las viviendas prefabricadas. El objetivo principal de esta iniciativa es proporcionar una herramienta eficiente que permita a nuestros clientes estimar el precio de una vivienda basándose en características clave, como los metros cuadrados, el número de habitaciones y baños, el material de fabricación, entre otros factores.\n",
    "\n",
    "---\n",
    "\n",
    "## Objetivo del Proyecto 🎯\n",
    "\n",
    "Con este proyecto, buscamos satisfacer las necesidades de nuestros futuros clientes, optimizando la eficiencia en diversas áreas: \n",
    "- Reducción de costes laborales y de tiempo\n",
    "- Mejora en la precisión de la fijación de precios\n",
    "- Identificación de patrones de compra\n",
    "- Predicción de la demanda\n",
    "- Minimización de la incertidumbre\n",
    "\n",
    "---\n",
    "\n",
    "## Estructura del Proyecto ✍🏻\n",
    "\n",
    "El proyecto se organiza en las siguientes secciones:\n",
    "\n",
    "### 1. Obtención de Datos 🔎\n",
    "\n",
    "Partimos desde cero, ya que nuestro cliente no contaba con los datos necesarios para trabajar. Por ello, decidimos obtenerlos utilizando la técnica de *Web Scraping* en la página web [Facilhouse](https://facilhouse.com/).\n",
    "\n",
    "Los detalles sobre la búsqueda de datos se encuentran en el archivo [web_scraping](data/web_scraping_facilhouse.ipynb), dentro de la carpeta [data](data). Además, el archivo CSV con los datos finales está disponible en [csv_data](data/facil_house.csv).\n",
    "\n",
    "Toda la información en formato HTML de las páginas de Facilhouse está disponible en la carpeta [html](html), de donde hemos utilizado herramientas como BeautifulSoup y Selenium para extraer los datos.\n",
    "\n",
    "### 2. Imágenes 🏞\n",
    "\n",
    "En la carpeta [imagenes](imagenes), encontrarás las imágenes utilizadas en este proyecto.\n",
    "\n",
    "### 3. Modelo: Entrenamiento y Resultados 🦾\n",
    "\n",
    "Todo el proceso de desarrollo del modelo se detalla en el archivo [memoria.ipynb](memoria.ipynb), que incluye:\n",
    "- Limpieza de datos\n",
    "- Creación del dataframe utilizado para entrenar los modelos\n",
    "- Resultados de los modelos entrenados (Random Forest, XGBoost y SVM)\n",
    "- Conclusiones obtenidas\n",
    "\n",
    "Una vez entrenado el modelo, lo exportamos a un archivo ➡️ [modelo_xgb.plk](modelo/modelo_xgb.pkl) para su posterior uso. También se generó un archivo para la normalización de los datos, el *Standard Scaler*, disponible en ➡️ [scaler_xgb.pkl](modelo/scaler_xgb.pkl).\n",
    "\n",
    "### 4. Aplicación 📲\n",
    "\n",
    "Para mejorar la experiencia del cliente, desarrollamos una aplicación basada en el modelo, permitiendo su uso diario en su trabajo. \n",
    "\n",
    "El archivo [app.py](app/app.py), que se encuentra en la carpeta [app](app), contiene la aplicación creada con Streamlit.\n",
    "\n",
    "Para facilitar la implementación en producción, hemos generado el archivo [requeriments.txt](requeriments.txt), que detalla todas las librerías necesarias para que la aplicación funcione correctamente.\n",
    "\n",
    "### 5. Otros Archivos\n",
    "\n",
    "Si deseas obtener una visión global del proyecto, puedes consultar la [presentación](presentacion_ml.ipynb), que resume todo el trabajo realizado.\n",
    "\n",
    "---\n",
    "\n",
    "Este proyecto tiene como fin proporcionar una solución robusta, práctica y accesible para predecir el valor de las viviendas prefabricadas, optimizando recursos y mejorando la toma de decisiones para nuestros clientes. ✌🏼"
   ]
  }
 ],
 "metadata": {
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
